spring:
  profiles:
    active: site1

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.apache.geode: INFO

---
spring:
  config:
    activate:
      on-profile: site1
  name: site1

gemfire:
  locator:
    port: 10334

management:
  metrics:
    export:
      logging:
        enabled: true
        step: 10s  # Interval at which metrics are pushed to the log
  endpoints:
    web:
      exposure:
        include: "*"


---
spring:
  config:
    activate:
      on-profile: site2
  name: site2

gemfire:
  locator:
    port: 20334

management:
  metrics:
    export:
      logging:
        enabled: true
        step: 10s  # Interval at which metrics are pushed to the log
  endpoints:
    web:
      exposure:
        include: "*"



